import{useEffect,useMemo,useState}from'react';
import{Brain,ClipboardList,LayoutGrid,Search,Settings as SettingsIcon,Star,Undo2,Users,X}from'lucide-react';
import{starterPlayers}from'./data';import{isDraftComplete,nextTurns,pickRound,pickTeam,positionCounts,rosterFor,snakeLabel}from'./draft';import{recommendations}from'./engine';import{load,save}from'./storage';import type{DraftState,Player,Position}from'./types';

type Tab='war'|'board'|'players'|'roster'|'ranks'|'settings';
const defaults:DraftState={picks:[],players:starterPlayers,teamNames:Array.from({length:14},(_,i)=>`Team ${i+1}`),settings:{teams:14,rounds:15,mySlot:1,roster:{QB:1,RB:2,WR:2,TE:1,K:1,DST:1}}};
const tabs:[Tab,string,typeof Brain][]=[['board','Board',LayoutGrid],['players','Players',Search],['war','War Room',Brain],['roster','Roster',Users],['ranks','Ranks',Star],['settings','Setup',SettingsIcon]];

export default function App(){
 const[state,setState]=useState<DraftState>(()=>load()??defaults),[tab,setTab]=useState<Tab>('war'),[query,setQuery]=useState(''),[pos,setPos]=useState<'ALL'|Position>('ALL');
 useEffect(()=>save(state),[state]);
 const current=state.picks.length+1,currentTeam=pickTeam(current,state.settings.teams),mine=currentTeam===state.settings.mySlot,recs=useMemo(()=>recommendations(state),[state]);
 const available=state.players.filter(p=>!state.picks.some(x=>x.playerId===p.id)).filter(p=>(pos==='ALL'||p.position===pos)&&p.name.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>a.rank-b.rank);
 const myRoster=rosterFor(state.picks,state.settings.mySlot,state.players),myNext=nextTurns(current-1,state.settings.mySlot,state.settings.teams,1)[0],update=(fn:(s:DraftState)=>DraftState)=>setState(s=>fn(s));
 const draft=(p:Player)=>{if(isDraftComplete(state.picks,state.settings))return;update(s=>({...s,picks:[...s.picks,{overall:current,round:pickRound(current,s.settings.teams),team:currentTeam,playerId:p.id}]}))};
 const remove=(id:string)=>update(s=>({...s,picks:s.picks.filter(p=>p.playerId!==id).map((p,i)=>({...p,overall:i+1,round:pickRound(i+1,s.settings.teams),team:pickTeam(i+1,s.settings.teams)}))}));
 return <div className="app">
  <header className="hero"><img src="./assets/dt-header-logo.png" alt="D&T Draft HQ"/><div className="status-grid"><div className="status main"><small>ON THE CLOCK</small><strong>{state.teamNames[currentTeam-1]}</strong><span>Round {pickRound(current,state.settings.teams)} · Pick {snakeLabel(current,state.settings.teams)}</span></div><div className="status"><small>YOUR NEXT TURN</small><strong>{myNext-current}</strong><span>picks away</span></div><div className="status"><small>DRAFTED</small><strong>{state.picks.length}</strong><span>of {state.settings.teams*state.settings.rounds}</span></div></div></header>
  <main>{tab==='war'&&<WarRoom recs={recs} mine={mine} draft={draft}/>} {tab==='players'&&<Players list={available} query={query} setQuery={setQuery} pos={pos} setPos={setPos} draft={draft}/>} {tab==='board'&&<Board state={state} remove={remove}/>} {tab==='roster'&&<Roster players={myRoster}/>} {tab==='ranks'&&<Ranks state={state} update={update}/>} {tab==='settings'&&<Setup state={state} update={update}/>}</main>
  {state.picks.length>0&&<button className="undo" onClick={()=>update(s=>({...s,picks:s.picks.slice(0,-1)}))}><Undo2 size={16}/> Undo pick</button>}
  <nav>{tabs.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={tab===id?'active':''}><Icon/><span>{label}</span></button>)}</nav>
 </div>
}

function WarRoom({recs,mine,draft}:{recs:ReturnType<typeof recommendations>;mine:boolean;draft:(p:Player)=>void}){const top=recs[0];return <><section className="section-head"><p className="eyebrow">LIVE DECISION ENGINE</p><h1>War Room</h1><p>{mine?'Your pick. Here’s the strongest path through the next bend.':'Planning ahead while the room picks.'}</p></section>{top&&<article className="card featured"><div className="card-top"><span className="pill">TOP PICK</span><span className="score">{Math.round(top.score)} path score</span></div><div className="player-title"><div className={`badge ${top.player.position}`}>{top.player.position}</div><div><h2>{top.player.name}</h2><p>{top.player.team} · Rank {top.player.rank} · Tier {top.player.tier}</p></div></div><div className="partner"><small>BEST REALISTIC PARTNER</small><strong>{top.partner?.name??'Reassess at the turn'}</strong><span>{top.partner?`${top.partner.position} · projected for your next pick`:''}</span></div><div className="metrics"><div><strong>{Math.round((1-top.survival)*100)}%</strong><span>wait risk</span></div><div><strong>{top.likelyGone.length}</strong><span>likely gone</span></div><div><strong>{top.path}</strong><span>future path</span></div></div><ul>{top.reasons.map(r=><li key={r}>{r}</li>)}</ul><p className="gone"><b>Likely gone:</b> {top.likelyGone.map(x=>x.name).join(', ')||'No clear locks'}</p>{mine&&<button className="primary" onClick={()=>draft(top.player)}>Draft {top.player.name}</button>}</article>}<h2 className="subhead">Top 3 recommendation paths</h2><div className="paths">{recs.map((r,i)=><article className="card path" key={r.player.id}><b className="path-num">0{i+1}</b><div className={`badge ${r.player.position}`}>{r.player.position}</div><div><h3>{r.player.name}</h3><p>{r.path}</p><small>{r.reasons[0]}</small></div></article>)}</div></>}
function Filter({query,setQuery,pos,setPos}:{query:string;setQuery:(x:string)=>void;pos:'ALL'|Position;setPos:(x:'ALL'|Position)=>void}){return <div className="filters"><label><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search players"/></label><select value={pos} onChange={e=>setPos(e.target.value as 'ALL'|Position)}>{['ALL','QB','RB','WR','TE','K','DST'].map(x=><option key={x}>{x}</option>)}</select></div>}
function Players({list,query,setQuery,pos,setPos,draft}:{list:Player[];query:string;setQuery:(x:string)=>void;pos:'ALL'|Position;setPos:(x:'ALL'|Position)=>void;draft:(p:Player)=>void}){return <><section className="section-head"><p className="eyebrow">DRAFT POOL</p><h1>Available players</h1><p>{list.length} players ready to draft.</p></section><Filter {...{query,setQuery,pos,setPos}}/><div className="list">{list.map(p=><article className="player-row" key={p.id}><b className="rank">{p.rank}</b><div className={`badge ${p.position}`}>{p.position}</div><div className="grow"><strong>{p.name}</strong><span>{p.team} · Tier {p.tier} · ADP {p.adp.toFixed(1)}</span></div><button onClick={()=>draft(p)}>Draft</button></article>)}</div></>}
function Board({state,remove}:{state:DraftState;remove:(id:string)=>void}){return <><section className="section-head"><p className="eyebrow">14-TEAM SNAKE</p><h1>Draft board</h1><p>Tap a drafted player to remove and rewind the board.</p></section><div className="board"><div className="board-grid" style={{gridTemplateColumns:`52px repeat(${state.settings.teams}, 124px)`}}><b>RD</b>{state.teamNames.map((n,i)=><b key={i}>{n}</b>)}{Array.from({length:state.settings.rounds},(_,r)=><FragmentRow key={r} r={r} state={state} remove={remove}/>)}</div></div></>}
function FragmentRow({r,state,remove}:{r:number;state:DraftState;remove:(id:string)=>void}){const cells=Array.from({length:state.settings.teams},(_,i)=>{const overall=r*state.settings.teams+(r%2?state.settings.teams-i:i+1),pick=state.picks.find(p=>p.overall===overall),pl=state.players.find(p=>p.id===pick?.playerId);return <button className={`board-cell ${pl?.position??''}`} key={i} onClick={()=>pl&&remove(pl.id)}><small>{overall}</small>{pl?<><b>{pl.name}</b><span>{pl.position} · {pl.team}</span></>:<i>—</i>}</button>});return <><b className="round">{r+1}</b>{cells}</>}
function Roster({players}:{players:Player[]}){const counts=positionCounts(players);return <><section className="section-head"><p className="eyebrow">YOUR TEAM</p><h1>Roster</h1><p>{players.length?`${players.length} players drafted`:'Your roster is waiting for its first pick.'}</p></section><div className="roster-strip">{Object.entries(counts).map(([k,v])=><div key={k}><b>{v}</b><span>{k}</span></div>)}</div><div className="list">{players.map((p,i)=><article className="player-row" key={p.id}><b className="rank">{i+1}</b><div className={`badge ${p.position}`}>{p.position}</div><div className="grow"><strong>{p.name}</strong><span>{p.team} · Rank {p.rank}</span></div></article>)}</div></>}
function Ranks({state,update}:{state:DraftState;update:(f:(s:DraftState)=>DraftState)=>void}){const move=(id:string,d:number)=>update(s=>{const ps=[...s.players].sort((a,b)=>a.rank-b.rank),i=ps.findIndex(p=>p.id===id),j=Math.max(0,Math.min(ps.length-1,i+d));[ps[i],ps[j]]=[ps[j],ps[i]];return{...s,players:ps.map((p,k)=>({...p,rank:k+1}))}});return <><section className="section-head"><p className="eyebrow">YOUR BOARD</p><h1>Rankings editor</h1><p>Changes autosave and immediately feed the War Room.</p></section><div className="list">{[...state.players].sort((a,b)=>a.rank-b.rank).map(p=><article className="player-row" key={p.id}><b className="rank">{p.rank}</b><div className={`badge ${p.position}`}>{p.position}</div><div className="grow"><strong>{p.name}</strong><span>{p.team} · Tier {p.tier}</span></div><div className="rank-btns"><button onClick={()=>move(p.id,-1)}>↑</button><button onClick={()=>move(p.id,1)}>↓</button></div></article>)}</div></>}
function Setup({state,update}:{state:DraftState;update:(f:(s:DraftState)=>DraftState)=>void}){const set=(key:'teams'|'rounds'|'mySlot',v:number)=>update(s=>({...s,settings:{...s.settings,[key]:v},teamNames:key==='teams'?Array.from({length:v},(_,i)=>s.teamNames[i]??`Team ${i+1}`):s.teamNames,picks:[]}));return <><section className="section-head"><p className="eyebrow">LEAGUE CONTROL</p><h1>Settings</h1><p>Structural changes reset the current draft to protect board integrity.</p></section><article className="card form"><label>League size<select value={state.settings.teams} onChange={e=>set('teams',+e.target.value)}>{Array.from({length:9},(_,i)=>i+8).map(x=><option key={x}>{x}</option>)}</select></label><label>Rounds<input type="number" min="10" max="20" value={state.settings.rounds} onChange={e=>set('rounds',+e.target.value)}/></label><label>My draft slot<select value={state.settings.mySlot} onChange={e=>set('mySlot',+e.target.value)}>{Array.from({length:state.settings.teams},(_,i)=>i+1).map(x=><option key={x}>{x}</option>)}</select></label></article><article className="card"><h2>Team names</h2>{state.teamNames.map((n,i)=><label className="team-name" key={i}><span>{i+1}</span><input value={n} onChange={e=>update(s=>({...s,teamNames:s.teamNames.map((x,j)=>j===i?e.target.value:x)}))}/></label>)}</article><button className="danger" onClick={()=>{if(confirm('Reset the entire draft and rankings?'))setStateSafe(update)}}>Reset all local data</button></>}
function setStateSafe(update:(f:(s:DraftState)=>DraftState)=>void){localStorage.clear();update(()=>defaults)}
